FS-1783: Relax errors for missing component status
metal-toolbox/fleetdb pull request #116
Opened 2024-11-08 21:47 UTC by sahil311289

This PR logs errors for missing component's status instead of erroring out.

2024-11-11 18:57 UTC, DoctorVin requested changes

2024-11-11 18:57 UTC, DoctorVin commented on internal/inventory/device_components.go
> +			zap.L().With(
You should include the error here as `zap.Error(err)` and then `Warn()` with something like "retrieving status versioned attribute"

Also, return the component without a `Status` field, so we have as much data in the response as we have in the database for this component.

2024-11-11 18:57 UTC, DoctorVin commented on internal/inventory/device_components.go
> +) (*rivets.ComponentAttributes, error) {
please don't break up these lines like this

2024-11-14 21:33 UTC, sahil311289 commented on internal/inventory/device_components.go
> +			zap.L().With(
Returning component without a `Status` if err- fixed.
Regarding the `zap.Error(err)`, I followed the error approach available in the file above:
```
switch {
		case err == nil, errors.Is(err, sql.ErrNoRows):
		case errors.As(err, &ute):
			// attributes are a bit of the wild-west. if the JSON we stored doesn't deserialize
			// cleanly into an attributes structure, just complain about it but don't stop.
			zap.L().With(
				zap.String("server.id", deviceID),
				zap.String("component.id", rec.ID),
				zap.String("component.type", rec.Name.String),
			).Warn("bad json attributes")
```
Would you still like me to change it to `zap.Error(err)`?

2024-11-14 22:04 UTC, DoctorVin approved these changes

2024-11-14 22:07 UTC, merged