FS-1101; Fixing fleetdb mod name
metal-toolbox/fleetdb pull request #14
Opened 2024-01-26 21:08 UTC by jakeschuurmans

Fixing fleetdb mod name

Bonus: Also adding a small script to make it easier to install crdb

2024-01-26 21:35 UTC, DoctorVin requested changes
I tried to mark every place I saw a `serverservice` or a `hollow`. We should get rid of all that junk in this pass as well.

I like the "install crdb" script but I wonder if it might be better to just document it?

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_firmware_set_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
I would prefer to not leave `serverservice` dangling here. Swap to `fleetdb` or the token of your choice.

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/mock_client_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
it's only a mock but this should be `fleetdb`

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_bom_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
`s/serverservice/fleetdb`

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_firmware_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
I will keep noting it too. 😅

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_int_test.go
> +	hollow "github.com/metal-toolbox/fleetdb/pkg/api/v1"
`hollow` doesn't have any meaning for us. `fleetdb` or `fleetdbApi` or whatever.

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_server_attributes_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
serverservice delenda est!

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_server_component_type_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
more token replacement

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_server_components_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
serverservice token

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_server_secret_types_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
Here too.

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_server_secrets_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
Token replacement

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/router_server_test.go
> +	serverservice "github.com/metal-toolbox/fleetdb/pkg/api/v1"
token replacement

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/server_component_type_service_test.go
> +	hollow "github.com/metal-toolbox/fleetdb/pkg/api/v1"
change `hollow` to something else please

2024-01-26 21:35 UTC, DoctorVin commented on pkg/api/v1/server_service_test.go
> +	hollow "github.com/metal-toolbox/fleetdb/pkg/api/v1"
I wonder if `hollow` means anything to anyone still here.

2024-01-26 21:35 UTC, DoctorVin commented on scripts/install_crdb.sh
I like the idea, but I wonder if there isn't an easier way via a package manager? I used `brew install cockroach`.

2024-01-29 14:50 UTC, jakeschuurmans commented on scripts/install_crdb.sh
I was simply following the instructions in the README. I keep forgetting homebrew exists. I just checked and apt and snap doesnt have it. I can rename this and remove the macOS side of it.

2024-01-29 20:12 UTC, jakeschuurmans commented
Once this is in, [this](https://github.com/equinixmetal/k8s-fleetdb/pull/21) can be merged.

2024-01-29 20:44 UTC, DoctorVin reviewed
A couple of mis-types?

2024-01-29 20:44 UTC, DoctorVin commented on Makefile
> +REPO := "https://github.com/metal-toolbox/fleet-scheduler.git"
`fleet-scheduler`?

2024-01-29 20:44 UTC, DoctorVin commented on README.md
>  > This means that support is best effort (at best!) and we strongly encourage you to NOT use this in production.
I only just saw that we still have this "It's untested and untrusted" thing here. We should ditch that, but if you don't want to in they PR add a Jira ticket.

2024-01-29 20:46 UTC, jakeschuurmans commented on Makefile
> +REPO := "https://github.com/metal-toolbox/fleet-scheduler.git"
Resolved.

2024-01-29 20:48 UTC, jakeschuurmans commented on README.md
>  > This means that support is best effort (at best!) and we strongly encourage you to NOT use this in production.
Done

2024-02-08 20:13 UTC, closed without merging