FS-1234; 99% done. Still need to fix Update test
metal-toolbox/fleetdb pull request #43
Opened 2024-04-25 22:25 UTC by jakeschuurmans

Adding Config Sets, unit tests, integration tests, mock tests, and the works to fleetdb.

There is more to talk about than can just be mentioned here in a description . . .

Main thing you might notice that might be alarming is I moved and renamed some of the "Attribute Operators". They have been moved to their own file "query_operators.go" so they can easily be shared

2024-04-30 15:01 UTC, jakeschuurmans commented on .github/workflows/lint-test.yml
> +        run: curl https://binaries.cockroachdb.com/cockroach-v21.1.21.linux-amd64.tgz | tar -xz && sudo cp -i cockroach-v21.1.21.linux-amd64/cockroach /usr/local/bin/
getting the CRDB error because the deprecated "crdb drop" command is no longer deprecated, and is now gone. The SQLBoiler version we use still uses drop.

2024-04-30 15:01 UTC, jakeschuurmans commented on Makefile
> +	grep -v "could not be registered in Prometheus\" error=\"duplicate metrics collector registration attempted\"" # TODO; Figure out why this message spams when tests fail
just a nice little filter to make integration tests much easier to read

2024-04-30 15:02 UTC, jakeschuurmans commented on Makefile
> +fresh-test: clean
We also have the talks in the README about building locally with Dockerfile.dev, but that docker takes much longer to build, so this method is much faster.

2024-04-30 15:03 UTC, jakeschuurmans commented on pkg/api/v1/attribute_list_params.go
> -type OperatorType string
Ripped all of this out and put it in its own file, query_operators.go

2024-04-30 15:05 UTC, jakeschuurmans commented on pkg/api/v1/query_operators.go
> +func OperatorURLQueryEncoder(rv reflect.Value) string {
If we swap out [urlquery](https://github.com/hetiansu5/urlquery/tree/master) for something else, these can be removed. Also if we replace the constants above with ints, these can be removed.

2024-04-30 15:05 UTC, jakeschuurmans commented on pkg/api/v1/query_operators.go
> +func appendOperatorQueryMod(mods []qm.QueryMod, comparitor OperatorComparitorType, name, value string) []qm.QueryMod {
Im hoping this function will make it easy for us to expand operators we want to support and greatly simplify query parsing code.

2024-05-02 10:43 UTC, joelrebel requested changes
Nice work here, thanks for improving on the query handling.

Going ahead I'd like us to consider https://github.com/cbrand/go-filterparams since its fairly comprehensive.

Left a few comments and suggestions.

2024-05-02 10:43 UTC, joelrebel commented on db/migrations/00002_config_sets.sql
> +CREATE TABLE public.config_sets (
can you rename this file and the tables to be `bios_config_sets` instead

2024-05-02 10:43 UTC, joelrebel commented on db/migrations/00002_config_sets.sql
> +    vendor STRING NULL,
I'd recommend both `vendor`, `model` be `NOT NULL` since each configuration applies to a specific piece of hardware

2024-05-02 10:43 UTC, joelrebel commented on db/migrations/00002_config_sets.sql
> +CREATE TABLE public.config_components (
Why is this called `_components`, should we call it something else since its easy mix up with it being related to `Server Components` some how?

2024-05-02 10:43 UTC, joelrebel commented on db/migrations/00002_config_sets.sql
> +    serial STRING NULL,
What serial number goes in here, I'd have thought - we'd almost never associate BIOS configurations with serial numbers, since thats way too specific?

2024-05-02 10:43 UTC, joelrebel commented on db/migrations/00002_config_sets.sql
> +    custom JSONB NULL,
whats the intention with the `custom` column, should it be called `raw` instead?

2024-05-02 10:43 UTC, joelrebel commented on pkg/api/v1/config_set.go
> +type ConfigSet struct {
Lets call this `BiosConfigSet` instead

2024-05-02 10:43 UTC, joelrebel commented on pkg/api/v1/config_set.go
> +	Components []ConfigComponent `json:"components" binding:"required"`
What does `Component` mean here, is it sections of the configuration?

2024-05-02 10:43 UTC, joelrebel commented on pkg/api/v1/router_responses.go
> +func deletedResponse2(c *gin.Context, count int64) {
This is helpful, can you add a deprecated comment on the existing `deletedResponse`, so we start to move over to the newer method and we can get rid of the older one.

2024-05-02 10:43 UTC, joelrebel commented on pkg/api/v1/router_responses.go
> +func dbErrorResponse2(c *gin.Context, message string, err error) {
Same as the above comment, would like us to move the rest of the code over to this method,
so add a deprecated comment on `dbErrorResponse`.

2024-05-02 10:43 UTC, joelrebel commented on pkg/api/v1/router.go
> +	// /server-config-sets
rename to `server-bios-config-sets`

2024-05-02 10:43 UTC, joelrebel commented on pkg/api/v1/router_config_set.go
> +	if dbSet.R != nil {
suggest returning early here so you can outdent the block below.
```
if dbSet.R == nil {
    return ...
}

for i := range...
```

2024-05-02 10:43 UTC, joelrebel commented on pkg/api/v1/router_config_set.go
> +		for i := range dbSet.R.FKConfigSetConfigComponents {
should we have a nil check on `dbSet.R` here as well?

2024-05-02 10:43 UTC, joelrebel commented on pkg/api/v1/router_config_set.go
> +func (r *Router) updateConfigSet(ctx context.Context, set *ConfigSet, oldDBSet *models.ConfigSet) (string, error) {
Given how involved this method is can you consider breaking it up into two - one that returns the items to insert, update, delete and this one to execute the db queries.

Aside, is it possible to use [Upsert](https://github.com/volatiletech/sqlboiler?tab=readme-ov-file#upsert) for the insert, updates?

2024-05-02 10:43 UTC, joelrebel commented on pkg/api/v1/router_config_set.go
> +
Can you add tests for this method - `updateConfigSet`

2024-05-02 11:20 UTC, jakeschuurmans commented on db/migrations/00002_config_sets.sql
> +    custom JSONB NULL,
raw is a better name for sure.

2024-05-03 15:32 UTC, jakeschuurmans commented on .github/workflows/lint-test.yml
> +        run: curl https://binaries.cockroachdb.com/cockroach-v21.1.21.linux-amd64.tgz | tar -xz && sudo cp -i cockroach-v21.1.21.linux-amd64/cockroach /usr/local/bin/
We have a ticket for it. FS-1400

2024-05-03 15:36 UTC, jakeschuurmans commented on Makefile
> +	@make push-image-devel
docker-up uses quickstart.yml. The image referenced in there is ghcr.io/metal-toolbox/fleetdb:latest.

That image is created from push-image-devel. docker-up doesnt build a new image for docker-compose. So we need to do that.

2024-05-03 15:38 UTC, jakeschuurmans commented on db/migrations/00002_config_sets.sql
> +    serial STRING NULL,
server components has serial
https://github.com/metal-toolbox/fleetdb/blob/63a0823cb0b27e52dfcbc313d1a8927b811385be/db/migrations/00001_init.sql#L33

2024-05-03 15:39 UTC, jakeschuurmans commented on pkg/api/v1/config_set.go
> +	Components []ConfigComponent `json:"components" binding:"required"`
Configuration Set for a machine, Configuration Component for a piece of the machine. So a collection of settings for a NIC or Motherboard.

2024-05-03 17:42 UTC, jakeschuurmans commented on pkg/api/v1/router_config_set.go
> +
I have this test here?
pkg/api/v1/router_bios_config_set_test.go:TestIntegrationServerBiosConfigSetUpdate()?

2024-05-06 12:58 UTC, joelrebel commented on db/migrations/00002_config_sets.sql
> +    serial STRING NULL,
Yeah, server components do have a `serial` field. I was curious why a BIOS Configuration set requires a serial attribute

2024-05-06 12:59 UTC, joelrebel commented on pkg/api/v1/config_set.go
> +	Components []ConfigComponent `json:"components" binding:"required"`
aha, thanks for explaining that

2024-05-06 13:06 UTC, joelrebel commented on pkg/api/v1/router_config_set.go
> +func (r *Router) updateConfigSet(ctx context.Context, set *ConfigSet, oldDBSet *models.ConfigSet) (string, error) {
True, the suggestion to use Upsert was only for the insert and update.
Although we can leave that optimisation for the next iteration of changes.

2024-05-07 12:54 UTC, joelrebel approved these changes
thanks, lets get this merged 🚀

2024-05-07 13:38 UTC, joelrebel approved these changes

2024-05-07 13:39 UTC, merged