Add firmware inband install method column, client request dumper
metal-toolbox/fleetdb pull request #48
Opened 2024-05-13 15:19 UTC by joelrebel

- Adds the `install_inband` bool column to identify firmware that must be installed inband.
- Pin sqlboiler version in Makefile.
- Add request dumper on the client to aid debugging requests and responses.

2024-05-13 15:35 UTC, jakeschuurmans commented on pkg/api/v1/requests.go
> +	if c.dumper != nil {
To clean this up a bit, could we just place the c.dumper nil check within dumpRequest and dumpResponse? I guess it would obfuscate when dumping happens, but a comment inside dumpRequest and dumpResponse would alleviate that.

2024-05-13 15:48 UTC, DoctorVin commented on pkg/api/v1/firmware.go
> +	// this has to be a pointer to a bool or the validator isn't happy.
Can you elaborate?

2024-05-13 15:48 UTC, DoctorVin commented on pkg/api/v1/requests.go
> +	if c.dumper != nil {
We could also capture that configuration in the client and embed this logic fully within making the request. That way once the client is instantiated no one else needs to know about it, it's all internal.

2024-05-13 15:51 UTC, jakeschuurmans commented on pkg/api/v1/router_firmware_test.go
> +				RepositoryURL: "https://example-bucket.s3.awsamazon.com/foobar",
did you mean to not set inband here?

2024-05-13 15:52 UTC, jakeschuurmans commented on pkg/api/v1/router_firmware_test.go
> +	var inbandFalse bool
is this super confusing just for me? Why not have a variable called "inband", and set it to true or false, or just set true or false on the "InstallInband" variable within ComponentFirmwareVersion. The intention is clear to just set it to false or true there instead of using two variables that just mean the opposite of each other.

2024-05-13 15:56 UTC, joelrebel commented on pkg/api/v1/router_firmware_test.go
> +				RepositoryURL: "https://example-bucket.s3.awsamazon.com/foobar",
Yep - not setting any `install_inband` value, causes the API validator to return the error as seen in that block

2024-05-13 15:58 UTC, joelrebel commented on pkg/api/v1/router_firmware_test.go
> +	var inbandFalse bool
This is because `ComponentFirmwareVersion.InstallInband` expects a pointer to a bool

2024-05-13 16:04 UTC, joelrebel commented on pkg/api/v1/firmware.go
> +	// this has to be a pointer to a bool or the validator isn't happy.
We want to make sure each `ComponentFirmwareVersion` payload always explicitly sets the `install_inband` to either `true` or `false` so that it does not have to be inferred on the API side. 
If `InstallInband` not a pointer to a bool, the validator is unable to verify the value was defined - a `false` value is considered as a value not set.

2024-05-13 16:15 UTC, jakeschuurmans commented on db/migrations/00003_add_install_inband_column.sql
> +ALTER TABLE public.component_firmware_version ADD COLUMN install_inband BOOL DEFAULT false;
why is `models.ComponentFirmwareVersion.InstallInband` a null bool? I guess by default the column is nullable unless specified to NOT NULL? Do we want this boolean to be nullable? I dont think we want install_inband to be null.

2024-05-13 16:15 UTC, jakeschuurmans requested changes
Have just a few questions I want answered.

2024-05-13 16:16 UTC, jakeschuurmans commented on pkg/api/v1/router_firmware_test.go
> +				RepositoryURL: "https://example-bucket.s3.awsamazon.com/foobar",
This also dives into my other [question](https://github.com/metal-toolbox/fleetdb/pull/48#discussion_r1598730418). Why do we want null bool?

2024-05-13 16:32 UTC, DoctorVin commented on pkg/api/v1/requests.go
> +	if c.dumper != nil {
It could, or we could provide multiple constructors so the default passes a `nil` `io.Writer` while one could be specialized for files (for external use) or stdout for tests. The test for logging in the client is then just `c.dumper != nil`.
There might be nuances that complicate this, but I think it should work.

2024-05-13 16:42 UTC, DoctorVin commented on pkg/api/v1/firmware.go
> +	// this has to be a pointer to a bool or the validator isn't happy.
Ack

2024-05-13 17:04 UTC, DoctorVin commented on db/migrations/00003_add_install_inband_column.sql
> +ALTER TABLE public.component_firmware_version ADD COLUMN install_inband BOOL DEFAULT false;
I would agree here. NULL doesn't make sense in this context (aside maybe a synonym for `false` but still).

2024-05-14 14:08 UTC, joelrebel commented on pkg/api/v1/firmware.go
> +	// this has to be a pointer to a bool or the validator isn't happy.
Included a comment to clarify this case.

2024-05-14 14:08 UTC, joelrebel commented on db/migrations/00003_add_install_inband_column.sql
> +ALTER TABLE public.component_firmware_version ADD COLUMN install_inband BOOL DEFAULT false;
Yep, this was my oversight, thanks for pointing it out! fixed in the latest set of changes.

2024-05-14 14:13 UTC, jakeschuurmans requested changes

2024-05-14 14:13 UTC, jakeschuurmans commented on pkg/api/v1/firmware.go
>  	InstallInband *bool     `json:"install_inband" binding:"required"`
remove the pointer. No longer needed.

2024-05-14 14:17 UTC, jakeschuurmans approved these changes

2024-05-14 14:38 UTC, DoctorVin approved these changes

2024-05-14 14:40 UTC, joelrebel commented on pkg/api/v1/firmware.go
>  	InstallInband *bool     `json:"install_inband" binding:"required"`
As discussed, this is required since we want the client to explicitly specify if the firmware is to be installed inband or not.

2024-05-14 14:42 UTC, joelrebel commented on pkg/api/v1/requests.go
> +	if c.dumper != nil {
fair point, we can iterate over this as we see necessary going ahead

2024-05-14 14:48 UTC, merged