[FS-1432]endpoint for firmware set selection
metal-toolbox/fleetdb pull request #54
Opened 2024-05-24 04:41 UTC by Alva8756

2024-05-24 11:50 UTC, joelrebel commented on pkg/api/v1/router_firmware_set.go
> +	if vendor := c.Query("vendor"); vendor != "" {
The vendor, model attributes can be set to be required and are expected as `&vendor=foo&model=bar`. If they are not passed in lets return an error.

The `organization`, `project` are arbitrary labels, so lets accept a URL parameter like `&labels=organization=b,project=c,another=d...`
which is parsed into a `map[string]string` and the selection code will search and return firmware sets that contain those labels exactly,
That way we don't hardcode `organization`, `project` and any new labels.

If there is no additional labels specified, our code should return the firmware set that includes the `default=true` label,
see https://fleet-docs.pages.equinixmetal.net/procedures/firmware-install/#labels-label for reference on how firmware sets are created.

2024-05-24 11:54 UTC, joelrebel commented on pkg/api/v1/router_firmware_set_test.go
> +func TestIntegrationListFirmwareSets(t *testing.T) {
I suggest adding some fixture data that looks like the firmware set we have in production (with default, latest, organization, project labels),
so that we can test each of these cases https://fleet-docs.pages.equinixmetal.net/procedures/firmware-install/#firmware-sets

for example,
1. Select query for firmware set with vendor, model returns the default, latest
2. Select query for firmware set with vendor, model, organization returns the latest

2024-05-24 11:57 UTC, joelrebel requested changes
This is a good start, I've left some suggestions.

2024-05-24 11:57 UTC, joelrebel commented on pkg/api/v1/server_service.go
> +	firmwareSetsEndpoint                = "firmware-sets/select"
Can we re-use the `server-component-firmware-sets` endpoint for this?

2024-05-24 11:57 UTC, joelrebel commented on pkg/api/v1/router.go
> +		srvFirmwareSets.GET("/select", amw.AuthRequired(readScopes("server-component-firmware-sets")), r.serverComponentFirmwareSetsSelect)
reuse the `srvCmpntFwSets` group so the endpoint would look like `/server-component-firmware-sets/select` ?

2024-05-24 11:59 UTC, joelrebel reviewed
One other suggestion is to add OpenAPI docs for the new endpoints and we add for the older ones over time.
Similar to https://github.com/metal-toolbox/conditionorc/blob/b202ef5e84ed7c29c547873c6c400f8dfa6c4d31/pkg/api/v1/routes/handlers.go#L182

2024-05-27 05:09 UTC, Alva8756 commented on pkg/api/v1/router_firmware_set.go
> +	if vendor := c.Query("vendor"); vendor != "" {
Done.
The params is formatted as `vendor=v&model=m&labels=k1=v1,k2=v2,etc`

2024-05-27 05:10 UTC, Alva8756 commented on pkg/api/v1/router_firmware_set_test.go
> +func TestIntegrationListFirmwareSets(t *testing.T) {
Thanks! Done added more test cases.
It looks it's not that clean to create more firmware-sets under existing `fixture.go`

2024-05-28 13:00 UTC, joelrebel requested changes
Alva, I think this endpoint needs to be merged into `serverComponentFirmwareSetList`.

Apologies, I did not realise this earlier, the parameters can then be passed in through `ComponentFirmwareSetListParams` , this would de-duplicate the code.

2024-05-31 13:36 UTC, joelrebel requested changes

2024-06-06 16:17 UTC, joelrebel approved these changes
Thanks for the efforts here!

2024-06-12 16:22 UTC, merged