Skus
metal-toolbox/fleetdb pull request #91
Opened 2024-07-23 12:55 UTC by jakeschuurmans

- Sku implementation
- Also a small fix for bios config set query list. If multiple child objects met the requirement for a query, the entry would be included twice.

2024-07-23 19:09 UTC, DoctorVin requested changes

2024-07-24 11:46 UTC, jakeschuurmans commented on pkg/api/v1/router_server_sku.go
> +	count, err := models.BiosConfigSets().Count(c.Request.Context(), r.DB)
thats awkward

2024-07-24 13:02 UTC, jakeschuurmans commented on pkg/api/v1/errors.go
> +	ErrNullRelation = errors.New("sqlboiler relation was unexpectedly null")
run-time error. Think this should just return a more generic error, then log it for us internally?

2024-07-24 13:07 UTC, jakeschuurmans commented on pkg/api/v1/server_sku.go
> +	AuxDevices       []ServerSkuAuxDevice `json:"aux_devices" binding:"required"`
Rename the types to AuxDevuce, Disk, Memory, and Nic?

2024-07-24 13:10 UTC, jakeschuurmans commented on pkg/api/v1/router_server_sku.go
> +func (r *Router) serverSkuList(c *gin.Context) {
Pagination will limit them.  pkg/api/v1/server_sku_params.go:192

2024-07-24 13:23 UTC, jakeschuurmans commented on pkg/api/v1/server_sku_nic.go
> +type ServerSkuNic struct {
i agree. Doesnt hurt to put it in there.

2024-07-24 15:55 UTC, jakeschuurmans commented on pkg/api/v1/router_server_sku.go
> +	defer loggedRollback(r, tx)
I cant think of a cleaner way to do it. Unless we want to throw that rollback with every error return. We could start wrapping these functions in a function that does this for you, but that too gets ugly.

2024-07-26 15:09 UTC, DoctorVin commented on pkg/api/v1/errors.go
> +	ErrNullRelation = errors.New("sqlboiler relation was unexpectedly null")
What circumstances would cause this? What's missing in this scenario?

2024-07-26 15:13 UTC, DoctorVin commented on pkg/api/v1/router_server_sku.go
> +	defer loggedRollback(r, tx)
I do [this](https://github.com/metal-toolbox/fleetdb/blob/1c33aa883246dabbb4a18d7a8176f96e9caccff5/pkg/api/v1/router_events.go#L258-L268) in the event history code. It's more verbose, but IMO less gross.

2024-07-26 15:33 UTC, DoctorVin commented on pkg/api/v1/server_sku.go
> +	UpdatedAt        time.Time            `json:"updated_at,omitempty"`
🤷 
I refuse to be bound by a precedent that may not fit the current situation. 😁 My opinion is that no one will care about this aside us. A SKU's updated time isn't as important as say, a condition's updated time, or some inventory updated time. That said, I'm not so adamant to remove it that I'll insist.

2024-07-26 15:48 UTC, DoctorVin commented on pkg/api/v1/router_server_sku.go
> +func (r *Router) serverSkuList(c *gin.Context) {
But that default is like 1000 records? That feels like information overload.

2024-07-26 15:49 UTC, DoctorVin commented on pkg/api/v1/router_server_sku.go
> +	count, err := models.BiosConfigSets().Count(c.Request.Context(), r.DB)
and also incorrect. 😂

2024-07-26 15:51 UTC, DoctorVin commented on pkg/api/v1/server_sku_params.go
> +func (p *ServerSkuListParams) setQuery(q url.Values) {
I'm kind of ambivalent about having folks just drop a SKU in as the query parameters, but OK. How does this code deal with a sparse structure?

2024-07-26 16:55 UTC, jakeschuurmans commented on pkg/api/v1/router_server_sku.go
> +func (r *Router) serverSkuList(c *gin.Context) {
default is 100 records. Max is 1000.
https://github.com/metal-toolbox/fleetdb/blob/1c33aa883246dabbb4a18d7a8176f96e9caccff5/pkg/api/v1/pagination.go#L15

2024-07-26 16:57 UTC, jakeschuurmans commented on pkg/api/v1/server_sku_params.go
> +func (p *ServerSkuListParams) setQuery(q url.Values) {
You mean empty variables? It ignores them.

2024-07-26 17:02 UTC, jakeschuurmans commented on pkg/api/v1/router_server_sku.go
> +	defer loggedRollback(r, tx)
that code does literally the same thing. tx.Rollback checks if tx.done before running a rollback. So we are not unconditionally rolling back.

2024-07-26 17:03 UTC, jakeschuurmans commented on pkg/api/v1/router_server_sku.go
> +	defer loggedRollback(r, tx)
its just WHERE we check.

2024-07-26 17:03 UTC, jakeschuurmans commented on pkg/api/v1/errors.go
> +	ErrNullRelation = errors.New("sqlboiler relation was unexpectedly null")
i ended up purging this code. But the scenario theoretically should never exist, was just "covering all bases".

2024-07-30 15:39 UTC, DoctorVin commented on pkg/api/v1/server_sku_test.go
no real client tests?

2024-07-30 15:39 UTC, DoctorVin commented on pkg/api/v1/router_server_sku.go
> +	defer loggedRollback(r, tx)
`loggedRollback` is doing the Rollback and disregarding the error if it's `ErrTxDone` instead of avoiding the error in the first place. I wouldn't care but in other APIs the cost of this error winds up being ~3 seconds.

2024-07-30 15:45 UTC, jakeschuurmans commented on pkg/api/v1/server_sku_test.go
Real client tests: https://github.com/metal-toolbox/fleetdb/blob/33bbc03ef6a4b16baa63a2a9ab6b2bf0c19512fe/pkg/api/v1/router_server_sku_test.go

2024-07-30 15:46 UTC, DoctorVin commented on pkg/api/v1/router_server_sku_test.go
> +// func TestIntegrationServerSkuUpdate(t *testing.T) {
Dead code?

2024-07-30 15:47 UTC, jakeschuurmans commented on pkg/api/v1/router_server_sku.go
> +	defer loggedRollback(r, tx)
The begginning of rollback does a atomic bool check and returns the err. Really think that check results in 3 seconds?
```
func (tx *Tx) rollback(discardConn bool) error {
	if !tx.done.CompareAndSwap(false, true) {
		return ErrTxDone
	}
	...
```

2024-07-30 15:49 UTC, jakeschuurmans commented on pkg/api/v1/router_server_sku_test.go
> +// func TestIntegrationServerSkuUpdate(t *testing.T) {
Oops. Forgot to uncomment. Thanks. Will push update.

2024-07-30 16:05 UTC, DoctorVin commented on pkg/api/v1/router_server_sku.go
> +	defer loggedRollback(r, tx)
I'm not concerned about  the error check. I'm more concerned about the layers of "OMG we got an error here." Today I caught a couple of logs from FleetDB where the latency was 4 sec with a rollback error immediately preceding it. However, checking another horribly latent response doesn't have that so... 🤷

2024-07-30 19:19 UTC, DoctorVin commented on pkg/api/v1/router_server_sku.go
> +	for i, auxDevice := range auxDevices {
Can't you "just" check to see if the auxDevice has a non-empty string ID? If ID is populated, update, otherwise insert?

2024-07-30 19:38 UTC, jakeschuurmans commented on pkg/api/v1/router_server_sku.go
> +	for i, auxDevice := range auxDevices {
will do that

2024-07-31 14:50 UTC, DoctorVin approved these changes

2024-07-31 16:37 UTC, iancoffey commented
Has there been any Product input on this?

2024-07-31 17:30 UTC, DoctorVin commented
> Has there been any Product input on this?

There hasn't, but SKUs are an internal concept meant to bridge between plans (which are totally under the control of Product) and the components view. Specifically it allows for a 1:N relationship where procured servers can be more easily matched with their plan with leaking non-plan component details outside our boundaries.

2024-08-02 12:04 UTC, merged